uwblueprint/dancefest-web

package-lock.json, package.json
Updates to dev dependencies to fix security vulnerabilities.
=> Fix security vulnerabilities 

src/components/adjudications/AdjudicationsSection.jsx, src/components/events/EventsSection.jsx, src/components/interface/Section.jsx, src/components/interface/SectionHeader.jsx, src/components/performances/PerformancesSection.jsx
Passes `performanceDialog` or `eventDialog` as a prop into section header to fix undefined `eventId` error.
=> Fixes Section Header Error

src/components/events/EventDialog.jsx, src/components/interface/Header.jsx, src/components/interface/SectionHeader.jsx, src/components/interface/settings/SettingsDropdown.jsx, src/components/settings/SettingsSection.jsx, src/components/styles.js, src/index.css
Introduced SettingsDropdown which gives you 2 options (Settings / Logout) in the top left corner.
Introduced a UI back button to improve navigation UX.
Events can now be deleted
=> Dropdown for settings / logout, back button & event deletion

src/components/events/EventForm.jsx, src/components/interface/AudioPlay.jsx, src/components/performances/PerformanceForm.jsx
Save button is only enabled if all fields of a Performance Form are filled
=> Performance Form data validation

src/components/interface/filter/index.jsx, src/components/performances/PerformancesSection.jsx
**What this PR does:** Adds search functionality to search for performances
Fixes Issue #42
=> Add Search Functionality

src/components/performances/PerformancesSection.jsx
This sorts all of our dances on the Performances page by danceEntry
=> Sort by DanceEntry on Performances

src/components/performances/PerformancesSection.jsx
Search checks for the existence of the keyword in the dance title, performers, and choreographers.
=> Fix search

src/components/adjudications/AdjudicationTableRow.jsx, src/components/adjudications/AdjudicationsSection.jsx
Adds Artistic and Technical Marks onto the UI.
=> Add Artistic / Technical

src/components/events/EventForm.jsx, src/components/events/EventsSection.jsx, src/components/interface/dialog/DialogInput.jsx, src/components/performances/PerformancesSection.jsx
Dropdown calendar implemented for date field of Event Form. If a date exists, the calendar auto-focuses on the date upon opening. If no date exists, default date is the current date.
=> Dropdown calendar for Event Form

src/components/adjudications/AdjudicationDialog.jsx, src/components/adjudications/AdjudicationTableRow.jsx, src/components/adjudications/AdjudicationsSection.jsx, src/components/interface/dialog/DialogReadOnly.jsx
Adjudication dialog now displays details of performance associated with the adjudication (dance title, performers, choreographers, school etc.)
=> Display performance fields in Adjudication Dialog 

firebase.json, src/components/adjudications/AdjudicationDialog.jsx, src/components/adjudications/AdjudicationTableRow.jsx, src/components/adjudications/AdjudicationsSection.jsx, src/components/performances/PerformanceForm.jsx, src/components/performances/PerformanceTableRow.jsx, src/components/performances/PerformancesSection.jsx
Filtering on size doesn't work because there's a discrepancy between "size" in our data model and "danceSize". So this converts everything to be under "danceSize"
Additionally: I've included a `firebase.json` which sets up `firebase deploy` from the command line allowing us to deploy an instance to firebase hosting.
=> Setup Firebase Deploy, Fix filtering on size

src/components/adjudications/AdjudicationDialog.jsx, src/components/adjudications/AdjudicationForm.jsx, src/components/adjudications/AdjudicationsSection.jsx, src/components/events/EventDialog.jsx, src/components/events/EventForm.jsx, src/components/interface/AudioPlay.jsx, src/components/interface/dialog/DFDialog.jsx, src/components/interface/editing/AlertDialog.jsx, src/components/performances/PerformanceDialog.jsx, src/components/performances/PerformanceForm.jsx, src/components/performances/PerformancesSection.jsx, src/components/settings/SettingsSection.jsx, src/constants.js, src/firebase/utils/batchUpdateData.js, src/firebase/utils/updateData.js, src/firebase/utils/updateSettings.js
* Adds ability to filter award considerations
* updates all `new` and `edit` strings into constants
* adds `this.subscibe()` to `componentWillUmount` to handle memory leaks with react state changes
=> Filter award considerations

src/components/performances/PerformancesSection.jsx
- fixed search bar bug by adding try catch block to PerformanceSection.js handleFilter()
- if invalid input is given, 0 matching performances will be displayed
=> fixed search bar bug

src/components/interface/AudioPlay.jsx
- change the audio player icon in the adjudication popup when audio is playing so that the user can see some feedback
=> add robust audio player icon

backend/db/seeds.py, backend/routes/performance_routes.py
Resulting sample response:
```{
"1": {
"artistic_mark": null,
"audio_url": null,
"cumulative_mark": null,
"id": 1,
"notes": null,
"performance_id": 1,
"special_award": null,
"tablet_id": null,
"technical_mark": null
},
"2": {
"artistic_mark": null,
"audio_url": null,
"cumulative_mark": null,
"id": 2,
"notes": null,
"performance_id": 1,
"special_award": null,
"tablet_id": null,
"technical_mark": null
},
"3": {
"artistic_mark": null,
"audio_url": null,
"cumulative_mark": null,
"id": 3,
"notes": null,
"performance_id": 1,
"special_award": null,
"tablet_id": null,
"technical_mark": null
}
}```
=> Adding adjudication get for a specific performance

package-lock.json, package.json
Ran `npm install axios --save` in order to add dependency to package.json and package-lock.json
=> Added axios HTTP client to npm dependencies

package-lock.json, package.json
To make this work:
npm install
make sure when you use it 
`import humps from 'humps';`
=> Enable humps for camel to snakecase

src/api/AdjudicationAPI.js, src/api/ApiUtils.js, src/api/PathConstants.js
This sets up the structure and shows an example get endpoint for adjudications.
=> Set up structure for client requests

src/api/performancesApi.js, src/components/performances/PerformancesSection.jsx
endpoint: /events//performances
gets the list of performances for a given event id
(you'll need to check the endpoint http://localhost:3000/events/1/performances to view results from the seed data)
=> get performances client endpoint

src/api/performanceApi.js, src/api/performancesApi.js, src/components/performances/PerformancesSection.jsx
Moved the getPerformances function to the same file as the post performance functions.
=> moved getPerformances to performanceApi file

backend/routes/performance_routes.py
GET performances
Parameters: awardId
Returns: {
performanceId: {
performanceId: <Int>
school: <string>
performers: Array<string>
danceTitle: <Int>
danceStyle: <string>
danceEntry: <Int>
danceSize: <String>
competitionLevel: <String>
choreographers: Array<string>
academicLevel: <string>
}
}
=> created get performances endpoint

backend/routes/performance_routes.py, src/api/AdjudicationAPI.js, src/api/performanceApi.js, src/components/adjudications/AdjudicationDialog.jsx, src/components/adjudications/AdjudicationForm.jsx, src/components/adjudications/AdjudicationTableRow.jsx, src/components/adjudications/AdjudicationsSection.jsx, src/components/performances/PerformancesSection.jsx
Note: this will not work yet until get events is merged.
=> Incorporating the adjudications request

backend/routes/performance_routes.py, backend/server.py, backend/utils/converters.py
Get adjudications for a list of `performance_id`
Response:
```
{performance_id: {adjudication_id: { ... }}}
```
=> Get multiple adjudications

backend/db/seeds.py, backend/routes/tablet_routes.py
* To create on get if missing like current logic
* Also added tablet info to seed
=> Update Tablet API

backend/db/__init__.py, backend/db/init_db.py, backend/db/models.py, backend/db/seeds.py, backend/migrations/versions/920b33a546fd_.py, backend/migrations/versions/b2976568d1c3_.py, backend/routes/adjudication_routes.py, backend/routes/award_routes.py, backend/routes/event_routes.py, backend/routes/mailer_routes.py, backend/routes/performance_routes.py, backend/routes/school_routes.py, backend/routes/tablet_routes.py, src/api/ApiUtils.js
also, formatting a lot of files
=> Namespace api

src/components/feedback/SchoolFeedbackPerformanceInfo.jsx, src/components/feedback/SchoolFeedbackPerformanceList.jsx, src/components/feedback/SchoolFeedbackSection.jsx
Todos:
- get new image for when no performance is selected (right now it says something about a nominated dance)
- get an image for when a bad link is accessed 
- maybe show more info?
=> new school feedback page

Pipfile
hardcoded dep versioning was breaking ability to generate pipfile.lock - updated to latest. works locally.
=> dependency fix

README.md
force pushing because abuse of power
=> update readme for dockerize backend

db/models.py, db/seeds.py, frontend/src/api/UserAPI.js, frontend/src/components/App.jsx, frontend/src/components/SignIn.jsx, routes/user_routes.py, server.py
- creating table in postgres to manage users
- linking with auth table in firebase
- backfilling data for test users
=> creating roles and users

frontend/src/components/events/EventTableRow.jsx
Reverts uwblueprint/dancefest-web#149
=> Revert "Opening events in new tab"

db/init_db.py, frontend/src/api/AdjudicationAPI.js, frontend/src/components/adjudications/AdjudicateForm.jsx, frontend/src/components/adjudications/AdjudicationSection.jsx, frontend/src/components/adjudications/AdjudicationTableRow.jsx, routes/adjudication_routes.py
- add a button in the adjudication form that navigates to the next performance to be evaluated and also one to go back one
- add a button to go to the first performance that hasn't been adjudicated by that judge
- need a new query for this one
- get adjudications by judge ID, order by ascending performance ID
- see if next performance exists (get call by ID)
- navigate to that specific adjudication page
=> Web Adjudication Navigation

frontend/src/api/AdjudicationAPI.js, frontend/src/components/adjudications/AdjudicationSection.jsx, frontend/src/components/adjudications/AdjudicationTableRow.jsx, routes/adjudication_routes.py
- ability to view that judge's scores on the table page
- ability to easily edit scores on the table page with a click
- get adjudication by performance ID and judge ID
- put adjudication (update) by performance ID and judge ID
=> Adjudication quick edit

frontend/src/components/adjudications/AdjudicationSection.jsx, frontend/src/components/adjudications/AdjudicationTableRow.jsx, frontend/src/components/performances/PerformancesSection.jsx, routes/event_routes.py
- we were calling get school API for every entry in performances (wasteful of network resources)
- turned naive query into join to get school name on first fetch
=> i hope employers see i made a PR on christmas

frontend/src/api/AdjudicationAPI.js, frontend/src/components/adjudications/AdjudicationSection.jsx, frontend/src/components/adjudications/AdjudicationTableRow.jsx, routes/adjudication_routes.py
- at the list level show which judges have or have not adjudicated
=> Adjudication admin view

frontend/src/components/Input.js, frontend/src/components/Modal.js, frontend/src/components/Tabs.js, frontend/src/pages/Performances.js, frontend/src/styles/components/Button.module.css, frontend/src/styles/components/Dropdown.module.css, frontend/src/styles/components/Input.module.css, frontend/src/styles/components/Layout.module.css, frontend/src/styles/components/Modal.module.css, frontend/src/styles/components/Tabs.module.css, frontend/src/styles/pages/Performances.module.css
Creating a PR to merge into dev to port into staging. Also created Tabs reusable component.
=> Performances page (WIP)

components/DatePicker.js, styles/DatePicker.scss, styles/Dropdown.scss, styles/globals.scss
- Adjust DatePicker styles per Julia's new design specs
- Make outline colour consistent across app
=> Adjust DatePicker styles

pages/api/settings/collect.js, pages/api/settings/delete.js, pages/settings.js, styles/pages/Settings.module.scss
- Connect settings page with settings API
- Frontend for Add School and Add Admin
=> Connect Settings page with Settings API

components/settings/AdminModal.js, components/settings/SchoolModal.js
=> [Bugfix]: Clear School/Admin modal fields after adding

components/Table.js, pages/settings.js
Quick fix for settings table bug
=> [Bugfix]: Small fix for settings page bug

components/Table.js, package.json, pages/performances/[id].js, pages/performances/index.js, styles/components/Layout.module.scss, styles/components/Table.module.scss, styles/pages/PerformanceDetails.module.scss
- Revert CSS width change
- Updated CSS for performances page to handle width change
- Update `package.json` to run pre-commit hook on `.scss` instead of `.css`
=> [Bugfix]: Revert CSS bug

components/settings/AdminModal.js, pages/api/user/create.js, pages/api/user/update/[id].js, pages/index.js, pages/settings.js, styles/components/settings/AdminModal.module.scss, styles/pages/Events.module.scss, styles/pages/Settings.module.scss
- Merge Admins, Judges and Staff tables into one Users table on Settings page
- Use dropdowns instead of email fields when setting judges in event modal
- Removed mysterious copyright symbol
Note:
- Could be cleaner with formatting functions in https://github.com/uwblueprint/dancefest-web/pull/212
=> [Improvement]: Update user management

components/Card.js, components/Layout.js, containers/Navigation.js, jsconfig.json, package.json, pages/_app.js, pages/api/events/collect.js, pages/api/events/get.js, pages/api/performances/collect.js, pages/event/[id].js, pages/index.js, pages/performances/index.js, styles/components/Layout.module.scss, yarn.lock
- Unstated Next
- Global event state hookup for performances and events page
- Navbar hookup
- Small bug fixes
=> [Feature]: Frontend state management

containers/Navigation.js, pages/awards/index.js, pages/index.js, pages/performances/index.js
- Reset global `event` to `null` upon going to `/`
- Add redirect to `/` on `/performances` and `/awards` if `event` is null
=> [Bugfix]: Fix state management

components/performances/PerformanceModal.js, pages/performances/index.js, utils/performances.js
=> [Fix]: Remove Academic Level

pages/api/awards/collect.js, pages/api/awards/get.js, pages/api/performances/collect.js
- Added setting ids to awards/collect, awards/get
- Added ability to filter performances by setting ids
=> [Feature]: Added setting ids for awards and filtering performances by setting id

components/AudioPlayer.js, components/AudioRecorder.js, components/performance-details/FeedbackAudio.js, components/performance-details/JudgeFeedback.js, package.json, styles/components/performance-details/FeedbackAudio.module.scss, yarn.lock
- Record judge feedback audio using [React Mic](https://github.com/cleandersonlobo/react-mic), which saves the audio data as a `Blob`. This blob is converted to an mp3 file and is uploaded to S3, after which the adjudication audio url is uploaded with the S3 file link
- The audio file only gets uploaded to S3 if the `Save` button is clicked
- If the audio is not rerecorded in editing mode, it will not be uploaded to S3 and the `Adjudication` DB entry's audio url is left unchanged
If no audio file has been recorded yet:
If there exists an audio file already:
While recording:
=> [Feature]: End-to-end audio recording with upload to S3

pages/awards/[id].js, styles/pages/AwardDetails.module.scss
Delete award button
- Need to get design verified
- Tested a few different scenarios and delete seems to work fine (deletes award, nominations and other related data)
- Added a confirmation modal for delete
=> [Feature]: Delete award button

components/Layout.js, components/performance-details/FeedbackAudio.js, components/performance-details/NewJudgeFeedback.js, components/performance-details/PerformanceSummary.js, components/performance-details/Tab.js, components/performances/EmptyTableComponent.js, components/performances/PerformancesTable.js, package.json, pages/api/schools/collect.js, pages/api/user/collect.js, pages/awards/[id].js, pages/awards/index.js, pages/performances/[id].js, pages/performances/index.js, pages/settings.js, prisma/seed.js, styles/components/Table.module.scss, styles/components/performance-details/Tab.module.scss, styles/pages/Awards.module.scss, styles/pages/PerformanceDetails.module.scss, utils/performances.js, yarn.lock
- Add judge view to screens across the app
- disable settings from navbar
- update awards and performances page to show data specific to judge
- disable adding or editing performances, deleting awards 
- Fix small dance title bug in the awards page
=> [Feature]: Judge View

components/awards/ScoreBasedAwards.js, pages/awards/[id].js, pages/awards/index.js, styles/pages/AwardDetails.module.scss, styles/pages/Awards.module.scss
**Bugfix**
- Hide Add Award button for judge view
**Feature**
- Add delete award button for score based awards
- Add audio player component to awards details
Should have broken this into multiple PR's but they're all small features so figured I'd get them in together. Can make separate PR's if needed
=> [Bugfix]: Judge Views

pages/feedback.js, pages/performances/[id].js
- Deploy failed due to Feedback page event destructuring issue if event was undefined/null
=> [Bugfix]: Fix destructuring bug on Feedback page

components/awards/AwardModal.js, components/performance-details/JudgeFeedback.js, pages/awards/[id].js, pages/awards/index.js, pages/performances/[id].js
- Add extra setting field for add award
- Disable switching tab while editing
- Disable filtering on awards page to not break app
=> [Feature]: Add extra setting field for add award

.env.sample, components/Layout.js, prisma/seed.js
**Description:** 
- Separate prod and dev seeding via environment variable (see .env sample)
- Bump version number
=> [Feature]: Per environment seeding for production

components/awards/AwardModal.js, components/awards/ScoreBasedAwards.js
- Fix score based awards crash
- Disable add award modal and clear values on submit/discard
=> [Bugfix]: Score Based awards + Add award modal error

styles/pages/Events.module.scss
- Fix misalignment of previous and next month buttons in DatePicker component
=> [Bugfix]: Fix previous and next month button alignment in DatePicker

pages/api/awards/edit.js, pages/api/awards/finalize.js, pages/api/awards/unfinalize.js, pages/api/events/collect.js, pages/api/events/create.js, pages/api/events/delete.js, pages/api/events/edit.js, pages/api/events/get.js, pages/api/feedback/index.js, pages/api/schools/collect.js, pages/api/schools/create.js, pages/api/schools/delete.js, pages/api/schools/get.js, pages/api/schools/update/[id].js, pages/api/settings/awards.js, pages/api/settings/collect.js, pages/api/settings/create.js, pages/api/settings/delete.js, pages/api/settings/get.js, pages/api/user/collect.js, pages/api/user/create.js, pages/api/user/update/[id].js, pages/api/user/upsert.js
- Changed res.send() to res.json() whenever appropriate
- Added 'return' infront of res just in case
=> [Bug]: Fixed backend crashing because multiple responses were being sent

components/settings/SchoolModal.js, package.json, pages/api/schools/create.js, pages/api/schools/update/[id].js, yarn.lock
- Added validation for phone number and email in the backend -> If either is invalid, it'll return 400 and will be displayed in the snackbar stating the error in the frontend
- Changed placeholder text to be example of phone number format and email format
=> [Feature] validate phone and email

components/awards/ScoreBasedAwards.js, pages/awards/index.js
- Add None option to the modal
- Remove unused ID from scorebased award table + fix missing performance name bug
=> [Feature]: None option in the Add Award modal

pages/api/user/create.js, pages/api/user/update/[id].js
- Added validating email for users in create and edit endpoints
=> [Feature]: Add email validation for user

components/performance-details/Tab.js, pages/awards/[id].js
Some places in the app showed artistic score before technical score, but we want to show technical score first.
=> [Improvement]: Reorder scores

components/Dropdown.js, components/events/EditEventModal.js, components/events/NewEventModal.js, pages/awards/[id].js
- Make `fixed` property for `Dropdown` component optional; only apply to Event modal
- Fix hard-coded "Event title"
- Fix award type showing enum
=> [Bugfix]: Small fixes

components/Table.js, pages/api/performances/collect.js, pages/api/performances/nominate.js, pages/awards/index.js
- Fix pre-filtering for score based awards
- Only check setting ID by the setting category they belong in
- Fix finalize bug for score based awards
- For awards_performances, only check if a performance is nominated for the specific award it's being nominated for
=> [Bugfix]: Fix score based filtering, finalize bug fix

pages/awards/[id].js
**Description**:
Change dance artistry and score based map capitalization.
=> [Improvement]: Change dance artistry capitalization

pages/awards/index.js, utils/csvParser.js
- Fix normal awards being duplicated in feedback CSV
- Fix deleting filters bug on Awards page
=> [Bugfix]: Final bug fixes

pages/awards/index.js
=> Hotfix: Finalized Table pagination bug

pages/awards/index.js, utils/csvParser.js
=> [Release]: v1.0.2

pages/api/feedback/index.js
Just editing the email template.
=> [Hotfix]: Update the email template
