- package-lock.json
- package.json
On a fresh setup for NPM, there's a dependency that cannot be resolved: `har-validator` returns a 404 on version 5.1.2. It appears that when they updated to 5.1.3, they removed 5.1.2 so I boosted our react-scripts version which solved the dependency on 5.1.2.
This can go into the start-firestore or master after we merge if I rebase.
> Fix setup error

- src/components/adjudications/AdjudicationForm.jsx
Found out our calculation is actually using string addition.
Ex. Technical Mark: "2", Artistic: "6", "2" + "6" = 26 / 2 = 13. This should be 4.
This fixes this.
> Fixing Adjudication Calculations

- src/components/events/EventForm.jsx
- src/components/interface/dialog/DialogInput.jsx
Event form now has placeholder text specifying the input format ("DD/MM/YYYY") in the event date field.
> Placeholder text for date field on event form

- src/components/interface/dialog/DialogInput.jsx
Remove DD/MM/YYYY as default DialogInput placeholder.
> Fix DialogInput Error

- src/components/adjudications/AdjudicationForm.jsx
Fix for Issue #46 
When Adjudication Form is submitted with the edits for `artisticMark`, `technicalMark`, `choreoAward`, and `specialAward`, the other fields of the adjudication object in the database are preserved.
> Save adjudication fields

- src/components/adjudications/AdjudicationForm.jsx
Updating Firebase from adjudication form no longer attempts to create new fields with undefined values.
> Fix for Adjudication Form sumbit bug

- README.md
- prisma/schema.prisma
- prisma/schema.sql
- prisma/seed.js
**Requires:** 
Schema change to due the addition of unique constraint in settings.
**Description:**
Add some basic seeding functionality.
Feel free to build on this and we will separate seeding in the future based on environment type.
**Testing:**
Run the following commands on an empty database (either reset your database or setup a new one):
```
heroku pg:psql -a YOUR_APP_NAME -f prisma/schema.sql
npx prisma introspect && npx prisma generate
npx prisma db seed --preview-feature
```
Verify that settings table and users table are populated with sample data.
> [Feature]: Data Seeding

- components/Modal.js
- components/settings/AdminModal.js
- components/settings/SchoolModal.js
- pages/api/settings/delete.js
- pages/api/user/create.js
Fixes the following bugs:
- Deleting setting value resulting in server error (due to not returning the `res.status(400)` in the API)
- Admin/school modal fields not resetting after closing the modal
- Admin/school still in editing mode even after API request succeeded (which caused new adds to edit the previously edited entry)
New:
- Raise a 400 when creating a new admin with an email that is already being used for another user
> [Bugfix]: Fix Settings page bugs

- components/performances/PerformancesTable.js
- styles/components/settings/AdminModal.module.scss
- Change number of rows per page in Performances Table from 3 to 20
- Fix a bug in Admin Modal where the Discard and Submit buttons were only clickable from a slim margin at the bottom
> [Bugfix]: Update Performances Table page size, Fix Admin Modal button bug

- pages/api/awards/collect.js
- pages/api/awards/create.js
- pages/api/awards/get.js
- pages/api/performances/collect.js
- pages/api/performances/get.js
- pages/api/performances/nominate.js
- prisma/schema.prisma
- prisma/schema.sql
**Requires:**
- Schema Upgrade
**Description:**
- Moved user_id field to awards_performances table 
- For the response of awards/collect.js, I changed the field name from 'award_performances' to 'performances' inside each awards object
> [Feature]: Moved user_id to awards_performances 

- pages/api/awards/collect.js
- pages/api/awards/finalize.js
- pages/api/awards/get.js
- pages/api/awards/unfinalize.js
- pages/api/performances/collect.js
- pages/api/performances/get.js
- pages/api/performances/nominate.js
- prisma/schema.prisma
- prisma/schema.sql
- prisma/seed.js
- Basic seeding into awards table and awards category table
- Added user_id to unique constraint to awards_performances tuple
- Removed nominee_count field from awards_performances
- Refactored existing routes to accommodate these changes 
- Tested nominating performance for multiple awards, tested nominating different performances for the same award, tested finalizing a performance for an award, tested attempting to finalize an award that is already finalized, which will throw an error.
- NOTE: Schema changes to this PR
> Feature awards seeding + removing nominee_count field and adding user_id to unique constraint for awards_performances

- prisma/seed.js
- Fixed issue of "unique constraint id failing" when creating new performances/records/events/etc. I think when I explicitly set the id, it wasn't autoincrementing which caused issues when we manually create.
> [Bugfix]: removed creating with explicitly set id in seeding

- components/performance-details/JudgeFeedback.js
- A user was able to manually input the cumulative score for a performance
- Disallow the cumulative score from being manually edited - calculate it automatically by averaging the technical and artistic scores
> [Bugfix]: Automatically calculate cumulative score

- components/Table.js
- components/performance-details/EditPerformanceModal.js
- components/performance-details/PerformanceSummary.js
- components/performances/AddPerformanceModal.js
- components/performances/PerformancesTable.js
- pages/performances/[id].js
- pages/performances/index.js
- styles/components/performance-details/PerformanceSummary.module.scss
- Removed the edit button from the Performances Table. When clicking on a row, the user will be linked to the Performance Details page for the selected performance
- In the Performance Modal, separated the Add functionality from the Edit functionality. Create is now the only option on the Performances Table page. Edit must be done through the Performance Details page
> [Improvement]: Change Performances Table routing, move Edit Performances Modal to Performance Details

- components/awards/AwardModal.js
- components/awards/ScoreBasedAwards.js
- components/performance-details/EditPerformanceModal.js
- components/performance-details/JudgeFeedback.js
- components/performances/AddPerformanceModal.js
- components/settings/AdminModal.js
- components/settings/SchoolModal.js
- pages/awards/[id].js
- pages/awards/index.js
- pages/index.js
- pages/performances/[id].js
- pages/performances/index.js
- pages/settings.js
Previously, buttons were still clickable after submitting a request using them. This caused event to be fired more than once, which was unideal, especially when it came to DB-modifying actions.
- Disabled all buttons that fire API requests while in loading states
> [Bugfix]: Disable button while in loading state

- pages/api/adjudications/delete.js
- pages/api/adjudications/edit.js
- pages/api/awards/delete.js
- pages/api/awards/edit.js
- pages/api/performances/delete.js
- pages/api/performances/edit.js
- pages/api/performances/nominate.js
- Check that adjudication exists
- If the performance associated with the adjudication is finalized, prevent deleting
- Delete all nominations with the same user_id as the user_iud in adjudication for the performance
- Check that adjudication exists
- If the performance associated with the adjudication is finalized, prevent editing -> Tested
- Check that award exists
- If the award is finalized, prevent deletion -> Tested
- Removed ability to set is_finalized through edit endpoint
- Check that award exists
- If the award is finalized, prevent editing
- If the award has nominations, prevent editing
- Check that performance exists
- If the performance has adjudications, prevent 
- If the performance is finalized, prevent deletion 
- Removed deleting award_performance records in cascading …
> [Feature]: backend validations for editing and deleting adjudications, performances, awards

- components/performance-details/FeedbackAudio.js
- styles/components/performance-details/FeedbackAudio.module.scss
- React-mic is bugged - on rerecord, it doesn't show the recording line
- Replaced the recording line with an audio recording animation from `react-loader-spinner`
> [Bugfix]: Fix recording animation not showing on rerecord

- pages/api/events/edit.js
- pages/index.js
- If the event has awards or performances, the backend will return a 400 error which will be displayed in the frontend.
- Allow editing event name or date but not judges if event has awards or performances
> [Feature]: Added validation to prevent editing event if it has performances or awards

- pages/performances/index.js
Fixes a few bugs with Performance filters:
- Deleting a filter pill deleted the actual filter option in the dropdown
- Spamming a filter option creates many duplicates of the pill, even when the filter state is current
> [Bugfix]: Fix deleting Performance filters

- components/awards/ScoreBasedAwards.js
- pages/api/performances/collect.js
- Added filtering for performances on score based awards page so that only performances eligible for the score based award are shown.
From the award_categories field of award, do we know which one corresponds to competition_level_id, dance_size_id, or dance_style_id? Right now, I have it send all the settingIDs in a list. If it's possible to know what each one corresponds to, I believe it would make the backend a bit cleaner since right now, for each of the 3 fields in performances, we're checking if the id is in the settingIDs array that's passed in.
> [Feature]: Added filtering for performances for score based awards

- pages/api/adjudications/create.js
- pages/performances/[id].js
When a judge was filling out the feedback for a performance, they were possibly shown the feedback given by another judge. This bug was due to the logic serving the adjudication not accounting for a judge.
> [Bugfix]: Fix judges seeing other judges' feedback

- components/Dropdown.js
- Set `Dropdown` menu to be fixed so that it is always on top and scrolling doesn't reposition it
> [Bugfix]: Fix judges dropdown forcing extra scroll when opening
